#!/system/bin/sh

if [ "$1" = "-?" -o "$1" = "-h" -o "$1" = "--help" ]; then
	echo "Usage:"
	echo "  $0 -?|-h|--help	Get help"
	echo "  $0 [port]		Start adb over network, default by 5555"
	echo "  $0 stop		Stop adb over network"
	echo "  $0 status		Get Status"
	exit
fi

# Get su
_su=""
for p in /sbin/su /system/sbin/su /system/bin/su /system/xbin/su /su/bin/su /magisk/.core/bin/su
do
  if [ -x $p ]; then
    _su="$p -c"
		break
	fi
done

# Check root
if [ -z "$_su" ]; then
  echo "No root!"
  exit 
fi

# Custom function
inPATH() {
	strings=$(echo "$PATH" | sed 's/:/ /g')
    for str in $strings
	do  
		if [ "$1" = "$str" ]; then
			return 0
		fi  
	done
	return 1
}

setPATH() {
	if ! inPATH "$1"; then
		PATH="$1:$PATH"
	fi
}

startAdbOverNetwork() {
	${_su} setprop service.adb.tcp.port "$1"
	echo "Start air adb. (Port: $1)"
}

# Set PATH
setPATH /system/bin
setPATH /sbin

PORT_DEFAULT=5555

if [ -z "$1" ]; then
	startAdbOverNetwork "$PORT_DEFAULT"
elif [ "$1" = "status" ]; then
	port="`${_su} getprop service.adb.tcp.port`"
	if [ -z "$port" ]; then
		echo "Is stopped"
		exit
	fi
	echo "Air adb is running (Port: $port)"
	exit
elif [ "$1" = "stop" ]; then
	port="`${_su} getprop service.adb.tcp.port`"
	if [ -z "$port" ]; then
		echo "Has stop"
		exit
	fi
	if command -v resetprop >/dev/null 2>&1; then
		${_su} resetprop --delete service.adb.tcp.port
	else
		${_su} setprop service.adb.tcp.port ""
	fi
	echo "Stop air adb. (Port: $port)"
else
	startAdbOverNetwork "$1"
fi

# Restart adbd
nohup $_su "stop adbd && start adbd" >/dev/null 2>&1 &
